<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta name="robots" content="noindex">
<meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>MathException Class Reference</title>
<link href="stylesheet.css" rel="stylesheet" type="text/css">
</head><body bgcolor="#ffffff">
<!-- Generated by Doxygen 1.2.3 on Thu Jul 19 13:03:32 2001 -->
<h1>MathException  Class Reference</h1>The class <code>MathException</code> provides methods for handling run-time errors and exceptions in mathematical operations that use the functions of the matrix library. 
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="MathException_hpp-source.html">MathException.hpp</a>&gt;</code>
<p>
<a href="class_MathException-members.html">List of all members.</a><table border=0 cellpadding=0 cellspacing=0>
<tr><td colspan=2><br><h2>Public Methods</h2></td></tr>
<tr><td nowrap align=right valign=top>&nbsp;</td><td valign=bottom><a class="el" href="class_MathException.html#a0">MathException</a> ()</td></tr>
<tr><td nowrap align=right valign=top>&nbsp;</td><td valign=bottom><a class="el" href="class_MathException.html#a1">~MathException</a> ()</td></tr>
<tr><td nowrap align=right valign=top>char*&nbsp;</td><td valign=bottom><a class="el" href="class_MathException.html#a2">getErrorMessage</a> ()</td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="class_MathException.html#a3">setErrorTypeIndexOutOfRange</a> ()</td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="class_MathException.html#a4">setErrorTypeSingularMatrix</a> ()</td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="class_MathException.html#a5">setErrorTypeDivideByZero</a> ()</td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="class_MathException.html#a6">setErrorTypeIncompatibleSize</a> ()</td></tr>
<tr><td nowrap align=right valign=top>void&nbsp;</td><td valign=bottom><a class="el" href="class_MathException.html#a7">setErrorTypeTypeMismatch</a> ()</td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
The class <code>MathException</code> provides methods for handling run-time errors and exceptions in mathematical operations that use the functions of the matrix library.
<p>
<b>Example Program:</b>
<p>
<div class="fragment"><pre><font class="comment">//========================================================================</font>
<font class="comment">// Project: Robotic Platform</font>
<font class="comment">// ----------------------------------------------------------------------</font>
<font class="comment">// Package      : The Math Library</font>
<font class="comment">// Authors      : Vilas Kumar Chitrakaran</font>
<font class="comment">// Start Date   : Wed Dec 20 11:08:28 GMT 2000</font>
<font class="comment">// Compiler     : GNU c++</font>
<font class="comment">// Operating System : QNX RTP</font>
<font class="comment">// ----------------------------------------------------------------------</font>
<font class="comment">// File: MathException.t.cpp</font>
<font class="comment">// Example program for the class MathExceptions.</font>
<font class="comment">//========================================================================  </font>
 

<font class="comment">// ----- Standard Libaries -----</font>
<font class="preprocessor">#include &lt;iostream.h&gt;</font>

<font class="comment">// ----- Project Includes -----</font>
<font class="preprocessor">#include "Matrix.hpp"</font>
<font class="preprocessor">#include "ColumnVector.hpp"</font>
<font class="preprocessor">#include "RowVector.hpp"</font>

<font class="comment">//======================================================================== </font>
<font class="comment">// main</font>
<font class="comment">//========================================================================  </font>
 
<font class="keywordtype">int</font> main()<font class="keyword"></font>
<font class="keyword"></font>{

  <a class="code" href="class_Matrix.html">Matrix&lt;4,3&gt;</a> M1;
  <a class="code" href="class_Matrix.html">Matrix&lt;3,4&gt;</a> M2;
  <a class="code" href="class_Matrix.html">Matrix&lt;3,3&gt;</a> M3;
  <a class="code" href="class_MatrixBase.html">MatrixBase&lt;&gt;</a> &amp;RefM1 = M1;
  <a class="code" href="class_MatrixBase.html">MatrixBase&lt;&gt;</a> &amp;RefM2 = M2;

  <a class="code" href="class_ColumnVector.html">ColumnVector&lt;4&gt;</a> C1;
  <a class="code" href="class_ColumnVector.html">ColumnVector&lt;3&gt;</a> C2;
  <a class="code" href="class_VectorBase.html">VectorBase&lt;&gt;</a> &amp;RefC1 = C1;
  <a class="code" href="class_VectorBase.html">VectorBase&lt;&gt;</a> &amp;RefC2 = C2;


  <a class="code" href="class_RowVector.html">RowVector&lt;3&gt;</a> R1;
  <a class="code" href="class_RowVector.html">RowVector&lt;4&gt;</a> R2;
  <a class="code" href="class_VectorBase.html">VectorBase&lt;&gt;</a> &amp;RefR1 = R1;
  <a class="code" href="class_VectorBase.html">VectorBase&lt;&gt;</a> &amp;RefR2 = R2;

<font class="comment">//---------------------------------------------------------------------------</font>
<font class="comment">// Each of the following operations will raise a MathException. The following</font>
<font class="comment">// lines of code show how to handle exceptions caused by illegal operations</font>
<font class="comment">// in the MathLibrary.</font>
<font class="comment">//---------------------------------------------------------------------------</font>

<font class="comment">// Assignment between two Matrix objects of different dimensions.</font>
  <font class="keywordflow">try</font>{
  M1 = M2;
  }
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    cout &lt;&lt; <font class="stringliteral">"M1 = M2: "</font> &lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }

<font class="comment">// Assignment between a reference to MatrixBase object and a Matrix object of different dimensions.</font>
  <font class="keywordflow">try</font>{
  <font class="comment">//M1 = RefM2;</font>
  RefM1 = M2;
  }
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    cout &lt;&lt; <font class="stringliteral">"M1 = RefM2 or RefM1 = M2: "</font> &lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }

<font class="comment">// Assignment between two references to MatrixBase objects of different dimensions.</font>
  <font class="keywordflow">try</font>{
  RefM1 = RefM2;
  }
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    cout &lt;&lt; <font class="stringliteral">"RefM1 = RefM2: "</font> &lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }

<font class="comment">// Assignment between two references to VectorBase objects of different dimensions.</font>
  <font class="keywordflow">try</font>{
  RefR1 = RefR2;
  }
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    cout &lt;&lt; <font class="stringliteral">"RefR1 = RefR2: "</font> &lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }

<font class="comment">// Assignment between a VectorBase reference and a Vector of a different size but same type.</font>
  <font class="keywordflow">try</font>{
  <font class="comment">//RefR1 = R2; // Each one of these will raise exceptions.</font>
  R2 = RefR1;
  }
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    cout &lt;&lt; <font class="stringliteral">"R2 = RefR1 or RefR1 = R2: "</font> &lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }

<font class="comment">// Assignment between two ColumnVector objects of different dimensions.</font>
  <font class="keywordflow">try</font>{
  C1 = C2;
  }
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    cout &lt;&lt;<font class="stringliteral">"C1 = C2: "</font> &lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }

<font class="comment">// Assignment between two RowVector objects of different dimensions.</font>
  <font class="keywordflow">try</font>{
  R1 = R2;
  }
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    cout &lt;&lt; <font class="stringliteral">"R1 = R2: "</font> &lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }

<font class="comment">// Assignment between a VectorBase object referenced to a ColumnVector and another ColumnVector object of different dimensions.</font>
  <font class="keywordflow">try</font>{
  C1 = RefC2;
  }
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    cout &lt;&lt; <font class="stringliteral">"C1 = RefC2: "</font> &lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }

<font class="comment">// Assignment between a VectorBase object referenced to a ColumnVector and another ColumnVector object of different dimensions.</font>
  <font class="keywordflow">try</font>{
  R1 = RefR2;
  }
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    cout &lt;&lt; <font class="stringliteral">"R1 = RefR2: "</font> &lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }

<font class="comment">// Assignment between two VectorBase references, one pointing to a RowVector and other to a ColumnVector.</font>
  <font class="keywordflow">try</font>{
  RefR2 = RefC2;
  }
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    cout &lt;&lt; <font class="stringliteral">"RefR2 = RefC2: "</font> &lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }

<font class="comment">// Assignment between a VectorBase reference and a Vector of a different type (column/row).</font>
  <font class="keywordflow">try</font>{
  RefR2 = C2; <font class="comment">// Each one of these will raise exceptions.</font>
  <font class="comment">//C1 = RefR1;</font>
  }
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    cout &lt;&lt; <font class="stringliteral">"C1 = RefR1 or RefR2 = C2: "</font> &lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }

<font class="comment">// Assignment between a RowVector and a ColumnVector.</font>
  <font class="keywordflow">try</font>{
  R1 = C2;
  }
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    cout &lt;&lt; <font class="stringliteral">"R1 = C2: "</font> &lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }


<font class="comment">// Indexing beyond the range of a non-scalar object.</font>
<font class="comment">// Each of the following will cause exceptions.</font>
  <font class="keywordtype">double</font> scalar;
  <font class="keywordflow">try</font>{
  scalar = M1(5,5);
  <font class="comment">//scalar = C1(6);</font>
  <font class="comment">//scalar = R1(6);</font>
  }
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    cout &lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }

<font class="comment">// Trying to find inverse of a singular matrix.</font>
  <font class="keywordflow">try</font>{
  inverse(M3);
  }
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    cout &lt;&lt; <font class="stringliteral">"inverse(M3): "</font>&lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }

<font class="comment">// Trying to divide a non-scalar type by zero.</font>
  <font class="keywordflow">try</font>{
  M1/0.0;
  }
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    cout &lt;&lt;<font class="stringliteral">"M1/0.0: "</font> &lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }

<font class="comment">// Trying to extract/fit a sub-matrix of improper dimensions from/to a matrix.</font>

  <a class="code" href="class_Matrix.html">Matrix&lt;2,2&gt;</a> subMatrix;
  <font class="keywordflow">try</font>{
  M1.<a class="code" href="class_Matrix.html#a11">setSubMatrix</a>(3,3,subMatrix); <font class="comment">// The subMatrix does not fit into the matrix.</font>
  }    
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    cout &lt;&lt;<font class="stringliteral">"M1.setSubMatrix(3,3,subMatrix): "</font> &lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }
  <font class="keywordflow">try</font>{
  M1.<a class="code" href="class_Matrix.html#a10">getSubMatrix</a>(3,3,subMatrix); <font class="comment">// The subMatrix does not fit into the matrix.</font>
  }    
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    cout &lt;&lt;<font class="stringliteral">"M1.getSubMatrix(3,3,subMatrix): "</font> &lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }

<font class="comment">// The functions \a isErrorType..() can be used to determine the type of</font>
<font class="comment">// of error that caused the exception. For exxample, lets try the divide by </font>
<font class="comment">// zero exception again...</font>

  <font class="keywordflow">try</font>{
  M1/0.0;
  }
  <font class="keywordflow">catch</font>(<a class="code" href="class_MathException.html">MathException</a> ex)
  {
    <font class="keywordflow">if</font>(ex.isErrorTypeSingularMatrix())
      cout &lt;&lt; <font class="stringliteral">"I want to do THIS for singular matrix exceptions."</font> &lt;&lt; endl;
    <font class="keywordflow">if</font>(ex.isErrorTypeDivideByZero())
      cout &lt;&lt; <font class="stringliteral">"I'm gonna do anything for you, but I won't do THAT."</font> &lt;&lt; endl;
    cout &lt;&lt;<font class="stringliteral">"M1/0.0: "</font> &lt;&lt; ex.getErrorMessage() &lt;&lt; endl;
  }

<font class="keywordflow">return</font> 0;
}
</div></pre> 
<p>
<hr><h2>Constructor &amp; Destructor Documentation</h2>
<a name="a0" doxytag="MathException::MathException"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td nowrap valign="top"><b> 
MathException (
          </b></td>
          <td valign="bottom"><b>
)<code> [inline]</code>
          </b></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
The default constructor.     </td>
  </tr>
</table>
<a name="a1" doxytag="MathException::~MathException"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td nowrap valign="top"><b> 
~MathException (
          </b></td>
          <td valign="bottom"><b>
)<code> [inline]</code>
          </b></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
The Default Destructor     </td>
  </tr>
</table>
<hr><h2>Member Function Documentation</h2>
<a name="a2" doxytag="MathException::getErrorMessage"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td nowrap valign="top"><b> 
char * getErrorMessage (
          </b></td>
          <td valign="bottom"><b>
)<code> [inline]</code>
          </b></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
return The error message string for a particular exception.     </td>
  </tr>
</table>
<a name="a3" doxytag="MathException::setErrorTypeIndexOutOfRange"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td nowrap valign="top"><b> 
void setErrorTypeIndexOutOfRange (
          </b></td>
          <td valign="bottom"><b>
)<code> [inline]</code>
          </b></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Sets the exception type to <em>e_exIndexOutOfRange</em>.     </td>
  </tr>
</table>
<a name="a4" doxytag="MathException::setErrorTypeSingularMatrix"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td nowrap valign="top"><b> 
void setErrorTypeSingularMatrix (
          </b></td>
          <td valign="bottom"><b>
)<code> [inline]</code>
          </b></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Sets the exception type to <em>e_exSingularMatrix</em>.     </td>
  </tr>
</table>
<a name="a5" doxytag="MathException::setErrorTypeDivideByZero"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td nowrap valign="top"><b> 
void setErrorTypeDivideByZero (
          </b></td>
          <td valign="bottom"><b>
)<code> [inline]</code>
          </b></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Sets the exception type to <em>e_exDivideByZero</em>.     </td>
  </tr>
</table>
<a name="a6" doxytag="MathException::setErrorTypeIncompatibleSize"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td nowrap valign="top"><b> 
void setErrorTypeIncompatibleSize (
          </b></td>
          <td valign="bottom"><b>
)<code> [inline]</code>
          </b></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Sets the exception type to <em>e_exIncompatibleMatrix</em>.     </td>
  </tr>
</table>
<a name="a7" doxytag="MathException::setErrorTypeTypeMismatch"></a><p>
<table width="100%" cellpadding="2" cellspacing="0" border="0">
  <tr>
    <td class="md">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td nowrap valign="top"><b> 
void setErrorTypeTypeMismatch (
          </b></td>
          <td valign="bottom"><b>
)<code> [inline]</code>
          </b></td>
        </tr>

      </table>
    </td>
  </tr>
</table>
<table cellspacing=5 cellpadding=0 border=0>
  <tr>
    <td>
      &nbsp;
    </td>
    <td>

<p>
Sets the exception type to <em>e_exTypeMismatch</em>.     </td>
  </tr>
</table>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="MathException_hpp-source.html">MathException.hpp</a></ul>
</body>
</html>
